### ISSUE TITLE
QuickSell altering the behavior of switching between tabs/menus (not in raid)

### ISSUE THREAD

**Issue by lexiconvict** [TadMaj/Tarkov-QuickSell#1]
After recently downloading this mod and adding it to the patch I'm playing (with various other mods installed) it seems that the "Tab" key function has changed in the main menu areas. It normally switches between the Character tab to the last tab you were on previously. For example, if I was in the trader menu looking through Mechanic items, normally I could press "Tab"  it would go back to my character inventory, then if I pressed "Tab" again, it would take me back to that same trader I was on (Mechanic in this example), and back and forth. With QuickSell installed, however, it doesn't do that. Instead, the "Tab" key would take me back to my character, but then if pressed again; would take me to the Flea Market. There was also some funky behaviour in the hideout happening, where, when pressing the "Esc" key it would take me to the Flea Market tab as well. I can't remember exactly now that it's back to normal and I don't feel like reinstalling to check, but I hope this bug report helps.

Also, perhaps there's weird interactions happening between your mod and the other mods I have installed, I haven't checked to see if this happens with only "QuickSell" installed. The bug stopped happening when removing only your mod though.

I am running SPT 3.9.8
Attached below are screenshots of my mod folders (with "QuickSell" removed) in case that helps:)

![Screenshot_27](https://github.com/user-attachments/assets/7a886ea5-b1a5-43ef-b9cc-d2732fe8f7d3)
![Screenshot_28](https://github.com/user-attachments/assets/51fbac13-48e4-42a0-a4b2-612712f5fa3e)

Also, I'm not 100% sure what version of your mod I downloaded as I don't see any information for the version number in the folder, and I see you released a few, quick updates. I believe I downloaded it 20-30 hours ago. I can try and figure that out if you know of any method to decipher that. I can send you the QuickSell-3.9.8 folder I have downloaded perhaps...

Cheers!
-Josh

**Comment by TadMaj** [comment]
Thanks for the detailed issue, i greatly appreciate it. This issue is probably due to how the mod loads the flea market prices. Hopefully will managed to release a fix soon :tm:
