### ISSUE TITLE
[ bug request ] ignores flea limit

### ISSUE THREAD

**Issue by gzhegow1991** [TadMaj/Tarkov-QuickSell#10]
Once i start using UIFixes for multiple selling, your feature will become super useful... I just move all the items from the raid to storage, select them with Shift, and then sell them at once.

But...

The feature ignores the Tarkov flea limit and becomes a cheat. Not actually ignores, some way it set limit below zero, and after that - limit is ignored until lots placed and still below zero.

If I select 100 items, all 100 items will be sold, and only the 101st item will tell me that I can't place more lots.

So far it works weirdly, sometimes you can sell items over the limit, sometimes you can't sell items if they are under the limit.

It would be great to fix this.

===

_P.S. could you make an additional simple mod that heals all body parts when you apply a first aid kit to a specific one? For example - you heal your hand for 30 hp, which means - all body parts get an additional 3 health points (10%). It doesn't matter if the first aid kit spends points on these 3 hp on each body part, the idea is to split the healing effect with a percentage, because Tarkov's damage is distributed to all body parts, and only the items like "yellow drug" heals everything (I don't want to use cheat drugs in a hardcore game)_

**Comment by gzhegow1991** [comment]
up

**Comment by TadMaj** [comment]
Yeah this was a bit of an oversight on my part, releasing a fix for this today.

**Comment by TadMaj** [comment]
Okay looked into it, unfortunitely, due to how bsg handles the flea market the item count in the flea market does not update fast enough for selling multiple different items. This is an issue that I am not willing to fix as it will require changing the netcode.

**Comment by gzhegow1991** [comment]
As a programmer i'll try to give you possible solution.

```
var limit;
var lastCheckTimestamp;
```

We dont use BSG limit, we create own layer between Tyfon and BSG, and there's a limit.

So idea is:
1. read BSG limit once per main menu coming, save it to `limit` var
2. save current time to `lastCheckTimestamp`
3. when you sell items - substract limit N times until it comes zero
4. if limit is already zero, force read BSG limit and update `limit` and `lastCheckTimestamp`
5. (optional) compare `lastCheckTimestamp` with `currentTimestamp` to calculate diff in seconds to reduce count of BSG reading. If diff < 5 seconds - use saved value, if > 5 seconds - read BSG value

Its about queues/buffers story. We dont need to setting up rabbit or redis, we can create buffer in source in few lines of code.

BSG limit can be read, just because of you did that before, otherwise Tyfon.UIFixes does.
