### ISSUE TITLE
[ Exceptions in console ] Inslalled latest 1.05 version, but on F12 EFT menu still visible that version is 1.02 and exceptions in console non-stop

### ISSUE THREAD

**Issue by gzhegow1991** [TadMaj/Tarkov-QuickSell#4]
sabge

**Comment by TadMaj** [comment]
Yeah I keep forgetting to increment the version number.

This should be fixed soon :tm:

Any clue about what kind of errors are you getting?

**Comment by gzhegow1991** [comment]
reference to null object or something

a lot of that exceptions, full console spammed out

but... it works perfectly as you design, it sells both directions. just flooding console
