### ISSUE TITLE
offtopic Fika server for tarkov SPT

### ISSUE THREAD

**Issue by MikeMasters** [TadMaj/Tarkov-QuickSell#5]
I saw that you made a Fika server for tarkov SPT.
https://hub.docker.com/r/tadikas/fika-server
Fika is now running 3.9.0. are you still maintaining this docker or is it possible the update somehow from within?

**Comment by TadMaj** [comment]
Hey, please keep my issues on topic.

If you reach out to me through spt hub dms ill be more than happy to help you once I have the time.
