### ISSUE TITLE
Repeated Error in Console

### ISSUE THREAD

**Issue by Rage-GitHub** [TadMaj/Tarkov-QuickSell#7]
This same error seems to be consistently repeating in my console, I presume nothing to really worry about.

Running on versions:
- **1.0.5 of QuickSell**
- **3.9.8 a0c79a of SPT** and
- **0.9.9015.15435 of Fika**

```
[Exception] : NullReferenceException: Object reference not set to an instance of an object
QuickSell.Patches.ConfigController.Update () (at <e94d819a560e482385e8a547c87ff66b>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class362:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

**Comment by TadMaj** [comment]
Yeah, this was a hotfix i put out in a rush and was too busy to fix it. Working on it now.
